name: CI

on:
  push:
    branches: main
  workflow_dispatch:
  schedule:
    # 3:02 everyday
    - cron: "2 1 * * *"

jobs:
  grab:
    timeout-minutes: 300
    strategy:
      matrix:
        ch:
          [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: install xmltv
        run: |
          source ./scripts/multi.sh
          install_xmltv
      - name: Run grabber
        run: |
          echo "all" | tv_grab_si --configure
          sort -o ~/.xmltv/tv_grab_si.conf ~/.xmltv/tv_grab_si.conf
          awk 'NR % 20 == ${{ matrix.ch }}' ~/.xmltv/tv_grab_si.conf > set.conf
          tv_grab_si --output "grab_${{ matrix.ch }}.xml" --config-file set.conf
      - name: Upload result
        uses: actions/upload-artifact@v4
        with:
          name: grab_${{ matrix.ch }}
          path: "grab_${{ matrix.ch }}.xml"
  pack:
    needs: [grab]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: Download all
        uses: actions/download-artifact@v4
        with:
          merge-multiple: true
      - name: Merge
        run: |
          source ./scripts/multi.sh
          install_xmltv
          ./scripts/merge.sh
          clr
      - name: Pack
        run: |
          zip -r epg.zip epg.xmltv
          gzip epg.xmltv
      - name: Update Nightly Release
        uses: andelf/nightly-release@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: latest
          name: "Najnovejši Spored"
          prerelease: true
          body: "Dnevno generiran spored"
          files: |
            ./*.xmltv
            ./*.gz
            ./*.zip
            README
      - name: Update Nightly Release
        uses: andelf/nightly-release@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.date.outputs.date }}
          name: "Spored ${{ steps.date.outputs.date }}"
          prerelease: true
          body: "Generiran ${{ steps.date.outputs.date }}"
          files: |
            ./*.xmltv
            ./*.gz
            ./*.zip
            README
